### ISSUE TITLE
Google Drive link is no longer valid

### ISSUE THREAD

**Issue by demonph10** [claws-lab/INPAC#4]
Hello~

I am deeply impressed by the excellent performance of your work and am currently studying your INPAC project.

I noticed that the Google Drive link is no longer valid. Could you please re-publish it? 

Thank you very much!

**Comment by Ahren09** [comment]
Hi @demonph10 ,

Thank you for the inquiries and apologies for the late replies! The datasets have been updated at https://huggingface.co/datasets/Ahren09/reddit to support easier loading.
